DATASET_NAME: "BIOSNAP_5fold"
MAX_ATOM_NODES: 551
MAX_DRUG_NODES: 2515 #1305
MAX_PROT_NODES: 1962 #1182
top_k_d: 100
top_k_t: 30
hidden_dim: 128
mol_dim: 768
prot_dim: 1280
atom_dim: 79
graph_dim: 64
conv_dim: 64
proj_dim: 64
LR: 0.0005
EPOCHS: 100 
BATCH_SIZE: 16
pos_weight: 1